# Generated by Django 4.2.4 on 2023-08-18 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Racks",
            fields=[
                ("rackId", models.AutoField(primary_key=True, serialize=False)),
                ("availableVerticalUnits", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Devices",
            fields=[
                ("deviceId", models.AutoField(primary_key=True, serialize=False)),
                ("deviceType", models.CharField(max_length=255)),
                ("modelName", models.CharField(max_length=255)),
                ("numberOfPorts", models.PositiveIntegerField()),
                ("verticalSize", models.PositiveIntegerField()),
                (
                    "rack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DataCenterApp.racks",
                    ),
                ),
            ],
        ),
    ]
